### ISSUE TITLE
gulp v4 version is not stable and not compatible with other packages

### ISSUE THREAD

**Issue by blackswanny** [godaddy/godaddy-test-tools#43]
it doesn't work with gulp-help being used in our projects, such as `gd-webapp-dev`. Updating of these projects to make only `gulpv4` work seems not so trivial and may not happen easily. Please, revert to 3.9 version of gulp
https://github.com/chmontgomery/gulp-help/issues/48
https://github.com/Semantic-Org/Semantic-UI/issues/6705
https://github.com/liferay/liferay-js-themes-toolkit/issues/69

**Comment by DullReferenceException** [comment]
Closing, obsolete issue.
